### SUCCES
GET http://localhost:8080/new-equipos/GE-001

### NOT FOUND
GET http://localhost:8080/new-equipos/1

### CREATE NEW EQUIPO VALID
POST http://localhost:8080/new-equipos
Content-Type: application/json

{
    "codigo": "GE-005",
    "nombre": "Grupo Electrógeno 05",
    "modelo": "Cummins QSB",
    "potencia": 400,
    "horometro": 0,
    "ubicacion": "Arequipa",
    "tipo": "Diesel",
    "estado": "Disponible"
}


### CREATE NEW EQUIPO INVALID
POST http://localhost:8080/new-equipos
Content-Type: application/json

{
    "codigo": "GP-005",
    "nombre": "Grupo Electrógeno 05",
    "modelo": "Cummins QSB",
    "potencia": 400,
    "horometro": 0,
    "ubicacion": "Arequipa",
    "tipo": "Diesel",
    "estado": "Disponible"
}