GET http://localhost:8080/new-equipos/1
###
GET http://localhost:8080/new-equipos/ubicacion/Arequipa
### 
POST http://localhost:8080/new-equipos
Content-Type: application/json

{
    "codigo": "GE-005",
    "nombre": "Grupo Electrógeno 05",
    "modelo": "Cummins QSB",
    "potencia": 400,
    "horometro": 0,
    "ubicacion": "Arequipa",
    "combustible": "Diesel",
    "estado": "Disponible"
}