spring.application.name=tests-productos


spring.datasource.url=jdbc:postgresql://ep-flat-rice-b4wkn91y-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ORAIH8UTjl7s

#Numero maximo de conexiones en el pool
spring.datasource.hikari.maximum-pool-size=1

# Tiempo máximo para obtener una conexión del pool 
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update